server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: bankModule
        uri: http://localhost:3001/
        predicates:
        - Path=/banks/**
      - id: customerModule
        uri: http://localhost:3002/
        predicates:
        - Path=/customers/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true
